### ISSUE TITLE
Não Traduziu

### ISSUE THREAD

**Issue by isanat** [Bleez/Magento2-PT-BR#18]
Ola desculpa a ignorancia, mas o meu na versão 2.1.5 só traduziu o backend, o frontend não foi traduzido nadinha. pode me orientar onde eu errei.
e o componente grid não abre fica so na tela de loading. olha o erro

An error occurred

An error occurred during execution; please try again later.

Additional information:

RuntimeException

File:
/home/wwwnacal/public_html/setup/src/Magento/Setup/Model/PackagesData.php:88
Message:
Couldn't get available versions for package bleez/magento2-pt_br
Stack trace:
#0 /home/wwwnacal/public_html/setup/src/Magento/Setup/Controller/ComponentGrid.php(98): Magento\Setup\Model\PackagesData->syncPackagesData()
#1 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
#2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /home/wwwnacal/public_html/setup/index.php(31): Zend\Mvc\Application->run()
#12 {main}

**Comment by isanat** [comment]
como desinstalar esta tradução?

**Comment by bcarvalho89** [comment]
Para desinstalar a tradução:
`composer remove bleez/magento2-pt_br`
